trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

workspace:
  clean: all

steps:
- script: |
    sudo apt-get install -y libcurl4-openssl-dev
  displayName: 'Install build dependencies'
- script: |
    set -e
    mkdir build
    cd build
    cmake ..
    make
  displayName: 'Build'
  workingDirectory: $(Build.SourcesDirectory)